// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../pkg/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as merger$0 from "../../pkg/merger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chanomhub$0 from "../../pkg/plugins/chanomhub/models.js";

/**
 * DeployLayer installs non-destructive JS translation layer (RPGM only)
 */
export function DeployLayer(gamePath: string, langName: string): $CancellablePromise<void> {
    return $Call.ByID(1710006594, gamePath, langName);
}

/**
 * ExportCopy patches files into a destination copy folder
 */
export function ExportCopy(gamePath: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(1736048213, gamePath, destPath);
}

/**
 * Merge reconciles current translations with an updated version of the game
 */
export function Merge(newGamePath: string): $CancellablePromise<merger$0.MergeStats | null> {
    return $Call.ByID(3215754690, newGamePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Publish archives and publishes mod to Chanomhub
 */
export function Publish(opts: app$0.PublishOptions): $CancellablePromise<chanomhub$0.PublishResult | null> {
    return $Call.ByID(2291432369, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = merger$0.MergeStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = chanomhub$0.PublishResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
