// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../../pkg/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Files returns a summary of all files and their translation progress
 */
export function Files(): $CancellablePromise<storage$0.FileSummary[]> {
    return $Call.ByID(1921931512).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Query retrieves paginated and filtered entries
 */
export function Query(q: storage$0.EntryQuery): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(3555135259, q).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Stats returns workspace metrics (total, translated, pending, percent)
 */
export function Stats(): $CancellablePromise<storage$0.WorkspaceStats> {
    return $Call.ByID(3779938036).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update updates the target text of an entry
 */
export function Update(id: string, target: string): $CancellablePromise<void> {
    return $Call.ByID(3801854380, id, target);
}

// Private type creation functions
const $$createType0 = storage$0.FileSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.QueryResult.createFrom;
const $$createType3 = storage$0.WorkspaceStats.createFrom;
