// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

export class QueryResult {
    "entries": model$0.TextEntry[];
    "total": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class Settings {
    /**
     * "mock", "gemini", "openai", "google", or any custom plugin name
     */
    "default_provider": string;

    /**
     * e.g. "gemini-2.5-flash", "gpt-4o-mini", etc.
     */
    "default_model": string;
    "gemini_api_key": string;
    "openai_api_key": string;
    "openai_base_url": string;
    "google_api_key": string;
    "chanomhub_token": string;
    "uchs_api_key": string;

    /**
     * dynamic map: provider_name -> api_key
     */
    "plugin_keys"?: { [_ in string]?: string };

    /**
     * dynamic map: provider_name -> base_url
     */
    "plugin_base_urls"?: { [_ in string]?: string };

    /**
     * "Japanese"
     */
    "default_source_lang": string;

    /**
     * "Thai"
     */
    "default_target_lang": string;

    /**
     * 10
     */
    "default_batch_size": number;

    /**
     * 4
     */
    "default_concurrency": number;

    /**
     * "dark"
     */
    "theme": string;
    "density"?: string;
    "font_size"?: string;
    "context_lore"?: string;
    "translation_style"?: string;
    "enable_memory_cache"?: boolean;

    /**
     * Task-Based AI Routing & Auxiliary System One (Hermes-Style Architecture)
     */
    "tasks": TasksConfig;
    "system_one": SystemOneConfig;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("default_provider" in $$source)) {
            this["default_provider"] = "";
        }
        if (!("default_model" in $$source)) {
            this["default_model"] = "";
        }
        if (!("gemini_api_key" in $$source)) {
            this["gemini_api_key"] = "";
        }
        if (!("openai_api_key" in $$source)) {
            this["openai_api_key"] = "";
        }
        if (!("openai_base_url" in $$source)) {
            this["openai_base_url"] = "";
        }
        if (!("google_api_key" in $$source)) {
            this["google_api_key"] = "";
        }
        if (!("chanomhub_token" in $$source)) {
            this["chanomhub_token"] = "";
        }
        if (!("uchs_api_key" in $$source)) {
            this["uchs_api_key"] = "";
        }
        if (!("default_source_lang" in $$source)) {
            this["default_source_lang"] = "";
        }
        if (!("default_target_lang" in $$source)) {
            this["default_target_lang"] = "";
        }
        if (!("default_batch_size" in $$source)) {
            this["default_batch_size"] = 0;
        }
        if (!("default_concurrency" in $$source)) {
            this["default_concurrency"] = 0;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if ("density" in $$source) {
            this["density"] = $$source["density"];
        }
        if ("font_size" in $$source) {
            this["font_size"] = $$source["font_size"];
        }
        if ("context_lore" in $$source) {
            this["context_lore"] = $$source["context_lore"];
        }
        if ("translation_style" in $$source) {
            this["translation_style"] = $$source["translation_style"];
        }
        if ("enable_memory_cache" in $$source) {
            this["enable_memory_cache"] = $$source["enable_memory_cache"];
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = (new TasksConfig());
        }
        if (!("system_one" in $$source)) {
            this["system_one"] = (new SystemOneConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType2;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugin_keys" in $$parsedSource) {
            $$parsedSource["plugin_keys"] = $$createField8_0($$parsedSource["plugin_keys"]);
        }
        if ("plugin_base_urls" in $$parsedSource) {
            $$parsedSource["plugin_base_urls"] = $$createField9_0($$parsedSource["plugin_base_urls"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField15_0($$parsedSource["tasks"]);
        }
        if ("system_one" in $$parsedSource) {
            $$parsedSource["system_one"] = $$createField16_0($$parsedSource["system_one"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SystemOneConfig specifies the auxiliary non-autoregressive decision engine (e.g. TypeSafe AI Jev)
 */
export class SystemOneConfig {
    /**
     * Auxiliary toggle (ON/OFF)
     */
    "enabled": boolean;

    /**
     * "typesafe_jev", "heuristic"
     */
    "provider": string;

    /**
     * TypeSafe AI API Key
     */
    "api_key": string;

    /**
     * Endpoint override (e.g. https://api.typesafe.ai/v1)
     */
    "base_url"?: string;

    /**
     * Minimum confidence score (e.g. 0.85)
     */
    "confidence_threshold": number;

    /**
     * Fine-grained delegation toggles
     */
    "features": SystemOneFeatures;

    /** Creates a new SystemOneConfig instance. */
    constructor($$source: Partial<SystemOneConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("confidence_threshold" in $$source)) {
            this["confidence_threshold"] = 0;
        }
        if (!("features" in $$source)) {
            this["features"] = (new SystemOneFeatures());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemOneConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemOneConfig {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField5_0($$parsedSource["features"]);
        }
        return new SystemOneConfig($$parsedSource as Partial<SystemOneConfig>);
    }
}

/**
 * SystemOneFeatures defines which decision delegations are enabled
 */
export class SystemOneFeatures {
    /**
     * Filter code vs text in gray-zone (Noul)
     */
    "filter_ambiguous_code": boolean;

    /**
     * Speculatively accept MT UI drafts without LLM (Noul)
     */
    "accept_ui_drafts": boolean;

    /**
     * Quality & refusal/hallucination sentinel (Score/Noul)
     */
    "verify_qa": boolean;

    /** Creates a new SystemOneFeatures instance. */
    constructor($$source: Partial<SystemOneFeatures> = {}) {
        if (!("filter_ambiguous_code" in $$source)) {
            this["filter_ambiguous_code"] = false;
        }
        if (!("accept_ui_drafts" in $$source)) {
            this["accept_ui_drafts"] = false;
        }
        if (!("verify_qa" in $$source)) {
            this["verify_qa"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemOneFeatures instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemOneFeatures {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemOneFeatures($$parsedSource as Partial<SystemOneFeatures>);
    }
}

/**
 * TaskBinding specifies model and options for a specific translation role
 */
export class TaskBinding {
    /**
     * "gemini", "openai", "google", "mock", or plugin name
     */
    "provider": string;

    /**
     * e.g. "gemini-2.5-pro", "gpt-4o", etc.
     */
    "model": string;

    /**
     * optional sampling temperature
     */
    "temperature"?: number;

    /**
     * optional token limit
     */
    "max_tokens"?: number;

    /** Creates a new TaskBinding instance. */
    constructor($$source: Partial<TaskBinding> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskBinding($$parsedSource as Partial<TaskBinding>);
    }
}

/**
 * TasksConfig manages Hermes-style task routing across different models
 */
export class TasksConfig {
    /**
     * Narrative / Complex dialogue
     */
    "primary_translation": TaskBinding;

    /**
     * UI, items, skills, bulk short text
     */
    "fast_translation": TaskBinding;

    /**
     * Route lines shorter than MaxShortLength to FastTranslation
     */
    "auto_route_short_text": boolean;

    /**
     * Character length threshold (default: 60)
     */
    "max_short_length": number;

    /**
     * Fallback engine if primary/fast fails
     */
    "fallback_translation": TaskBinding;

    /**
     * Enable automatic failover to fallback provider
     */
    "enable_fallback": boolean;

    /** Creates a new TasksConfig instance. */
    constructor($$source: Partial<TasksConfig> = {}) {
        if (!("primary_translation" in $$source)) {
            this["primary_translation"] = (new TaskBinding());
        }
        if (!("fast_translation" in $$source)) {
            this["fast_translation"] = (new TaskBinding());
        }
        if (!("auto_route_short_text" in $$source)) {
            this["auto_route_short_text"] = false;
        }
        if (!("max_short_length" in $$source)) {
            this["max_short_length"] = 0;
        }
        if (!("fallback_translation" in $$source)) {
            this["fallback_translation"] = (new TaskBinding());
        }
        if (!("enable_fallback" in $$source)) {
            this["enable_fallback"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TasksConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TasksConfig {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType6;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary_translation" in $$parsedSource) {
            $$parsedSource["primary_translation"] = $$createField0_0($$parsedSource["primary_translation"]);
        }
        if ("fast_translation" in $$parsedSource) {
            $$parsedSource["fast_translation"] = $$createField1_0($$parsedSource["fast_translation"]);
        }
        if ("fallback_translation" in $$parsedSource) {
            $$parsedSource["fallback_translation"] = $$createField4_0($$parsedSource["fallback_translation"]);
        }
        return new TasksConfig($$parsedSource as Partial<TasksConfig>);
    }
}

export class TranslationDonePayload {
    "success": boolean;
    "error"?: string;

    /** Creates a new TranslationDonePayload instance. */
    constructor($$source: Partial<TranslationDonePayload> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationDonePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationDonePayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationDonePayload($$parsedSource as Partial<TranslationDonePayload>);
    }
}

// Private type creation functions
const $$createType0 = model$0.TextEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = TasksConfig.createFrom;
const $$createType4 = SystemOneConfig.createFrom;
const $$createType5 = SystemOneFeatures.createFrom;
const $$createType6 = TaskBinding.createFrom;
