// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

export class QueryResult {
    "entries": model$0.TextEntry[];
    "total": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class TaskBinding {
    "provider": string;
    "model": string;
    "temperature"?: number;
    "max_tokens"?: number;

    constructor($$source: Partial<TaskBinding> = {}) {
        this["provider"] = $$source["provider"] || "";
        this["model"] = $$source["model"] || "";
        if ("temperature" in $$source) this["temperature"] = $$source["temperature"];
        if ("max_tokens" in $$source) this["max_tokens"] = $$source["max_tokens"];
        Object.assign(this, $$source);
    }
}

export class SystemOneFeatures {
    "filter_ambiguous_code": boolean;
    "accept_ui_drafts": boolean;
    "verify_qa": boolean;

    constructor($$source: Partial<SystemOneFeatures> = {}) {
        this["filter_ambiguous_code"] = $$source["filter_ambiguous_code"] ?? true;
        this["accept_ui_drafts"] = $$source["accept_ui_drafts"] ?? true;
        this["verify_qa"] = $$source["verify_qa"] ?? false;
        Object.assign(this, $$source);
    }
}

export class SystemOneConfig {
    "enabled": boolean;
    "provider": string;
    "api_key": string;
    "base_url"?: string;
    "confidence_threshold": number;
    "features": SystemOneFeatures;

    constructor($$source: Partial<SystemOneConfig> = {}) {
        this["enabled"] = $$source["enabled"] ?? false;
        this["provider"] = $$source["provider"] || "typesafe_jev";
        this["api_key"] = $$source["api_key"] || "";
        if ("base_url" in $$source) this["base_url"] = $$source["base_url"];
        this["confidence_threshold"] = $$source["confidence_threshold"] ?? 0.85;
        this["features"] = new SystemOneFeatures($$source["features"] || {});
        Object.assign(this, $$source);
    }
}

export class TasksConfig {
    "primary_translation": TaskBinding;
    "fast_translation": TaskBinding;
    "auto_route_short_text": boolean;
    "max_short_length": number;

    constructor($$source: Partial<TasksConfig> = {}) {
        this["primary_translation"] = new TaskBinding($$source["primary_translation"] || {});
        this["fast_translation"] = new TaskBinding($$source["fast_translation"] || {});
        this["auto_route_short_text"] = $$source["auto_route_short_text"] ?? false;
        this["max_short_length"] = $$source["max_short_length"] ?? 60;
        Object.assign(this, $$source);
    }
}

export class Settings {
    /**
     * "mock", "gemini", "openai", "google"
     */
    "default_provider": string;

    /**
     * e.g. "gemini-2.5-flash", "gpt-4o-mini"
     */
    "default_model": string;
    "gemini_api_key": string;
    "openai_api_key": string;
    "openai_base_url": string;
    "google_api_key": string;
    "chanomhub_token": string;
    "uchs_api_key"?: string;
    "plugin_keys"?: Record<string, string>;
    "plugin_base_urls"?: Record<string, string>;

    /**
     * "Japanese"
     */
    "default_source_lang": string;

    /**
     * "Thai"
     */
    "default_target_lang": string;

    /**
     * 10
     */
    "default_batch_size": number;

    /**
     * 4
     */
    "default_concurrency": number;

    /**
     * "dark"
     */
    "theme": string;

    /** Task-Based AI Routing & System One Auxiliary */
    "tasks"?: TasksConfig;
    "system_one"?: SystemOneConfig;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("default_provider" in $$source)) {
            this["default_provider"] = "";
        }
        if (!("default_model" in $$source)) {
            this["default_model"] = "";
        }
        if (!("gemini_api_key" in $$source)) {
            this["gemini_api_key"] = "";
        }
        if (!("openai_api_key" in $$source)) {
            this["openai_api_key"] = "";
        }
        if (!("openai_base_url" in $$source)) {
            this["openai_base_url"] = "";
        }
        if (!("google_api_key" in $$source)) {
            this["google_api_key"] = "";
        }
        if (!("chanomhub_token" in $$source)) {
            this["chanomhub_token"] = "";
        }
        if (!("default_source_lang" in $$source)) {
            this["default_source_lang"] = "";
        }
        if (!("default_target_lang" in $$source)) {
            this["default_target_lang"] = "";
        }
        if (!("default_batch_size" in $$source)) {
            this["default_batch_size"] = 0;
        }
        if (!("default_concurrency" in $$source)) {
            this["default_concurrency"] = 0;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class TranslationDonePayload {
    "success": boolean;
    "error"?: string;

    /** Creates a new TranslationDonePayload instance. */
    constructor($$source: Partial<TranslationDonePayload> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationDonePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationDonePayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationDonePayload($$parsedSource as Partial<TranslationDonePayload>);
    }
}

// Private type creation functions
const $$createType0 = model$0.TextEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
