// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as registry$0 from "../../pkg/registry/models.js";

/**
 * Close closes the currently open workspace
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1649113468);
}

/**
 * CreateFromGame extracts translatable strings and creates a new workspace (.nst)
 */
export function CreateFromGame(gamePath: string, wsPath: string, srcLang: string, tgtLang: string, ...engine: string[]): $CancellablePromise<model$0.ExtractionStats | null> {
    return $Call.ByID(2945709566, gamePath, wsPath, srcLang, tgtLang, engine).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Current returns current open project metadata, or nil if none open
 */
export function Current(): $CancellablePromise<model$0.Project | null> {
    return $Call.ByID(1159903181).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DetectEngine checks game engine type for a directory
 */
export function DetectEngine(dir: string): $CancellablePromise<string> {
    return $Call.ByID(3114172169, dir);
}

/**
 * List returns all registered projects with up-to-date translation progress
 */
export function List(): $CancellablePromise<registry$0.ProjectEntry[]> {
    return $Call.ByID(165469264).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenWorkspace opens a .nst workspace file and attaches it to the current session
 */
export function OpenWorkspace(path: string): $CancellablePromise<model$0.Project | null> {
    return $Call.ByID(1456724877, path).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PickDirectory opens a native directory picker dialog
 */
export function PickDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(3000043676, title);
}

/**
 * PickWorkspace opens a native file picker dialog for .nst workspace
 */
export function PickWorkspace(save: boolean): $CancellablePromise<string> {
    return $Call.ByID(2263180898, save);
}

/**
 * RemoveFromRegistry removes a workspace entry from the registry (does NOT delete file)
 */
export function RemoveFromRegistry(path: string): $CancellablePromise<void> {
    return $Call.ByID(876990823, path);
}

// Private type creation functions
const $$createType0 = model$0.ExtractionStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Project.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = registry$0.ProjectEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
