// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings reads persisted settings or returns defaults
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings writes updated settings to disk
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2662658340, settings);
}

/**
 * RequestUchsKey requests a new Virtual Key from Chanomhub
 */
export function RequestUchsKey(): $CancellablePromise<string> {
    return $Call.ByName("main.SettingsService.RequestUchsKey");
}

/**
 * OpenUchsPortal opens the UCHS Account Portal in the default web browser via Chanomhub SSO
 */
export function OpenUchsPortal(): $CancellablePromise<void> {
    return $Call.ByName("main.SettingsService.OpenUchsPortal");
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
