// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../pkg/app/models.js";
import * as custom$0 from "../../pkg/translator/custom/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetProviders returns list of all built-in and plugin translation providers
 */
export function GetProviders(): $CancellablePromise<app$0.ProviderInfo[]> {
    return $Call.ByID(3346709858).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSettings reads persisted settings or returns defaults
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenUchsPortal opens the UCHS Account Portal in the default web browser via Chanomhub SSO.
 * If token is provided, it updates the saved Chanomhub token; otherwise it uses the persisted token.
 */
export function OpenUchsPortal(token: string): $CancellablePromise<void> {
    return $Call.ByID(934247943, token);
}

/**
 * RequestUchsKey requests a new Virtual Key from Chanomhub and saves it into settings.
 * If token is provided, it updates the saved Chanomhub token; otherwise it uses the persisted token.
 */
export function RequestUchsKey(token: string): $CancellablePromise<string> {
    return $Call.ByID(1512064863, token);
}

/**
 * SaveSettings writes updated settings to disk
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2662658340, settings);
}

/**
 * SaveCustomProvider saves or updates a custom provider plugin definition (~/.lingo/providers/<name>.json)
 */
export function SaveCustomProvider(def: custom$0.Definition): $CancellablePromise<void> {
    return $Call.ByID(399115247, def);
}

/**
 * DeleteCustomProvider removes a custom provider plugin definition
 */
export function DeleteCustomProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(3056671089, name);
}

/**
 * ListCustomProviders returns all saved custom provider definitions
 */
export function ListCustomProviders(): $CancellablePromise<custom$0.Definition[]> {
    return $Call.ByID(3278852807).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FetchRemoteModels queries an OpenAI-compatible or Ollama endpoint for available models
 */
export function FetchRemoteModels(baseURL: string, apiKey: string): $CancellablePromise<string[]> {
    return $Call.ByID(731427188, baseURL, apiKey).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * TestCustomProvider verifies connection by translating a sample word
 */
export function TestCustomProvider(def: custom$0.Definition): $CancellablePromise<string> {
    return $Call.ByID(2007263554, def);
}

// Private type creation functions
const $$createType0 = app$0.ProviderInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $Create.Array(custom$0.Definition.createFrom);
const $$createType4 = $Create.Array($Create.Any);

