// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../pkg/app/models.js";

/**
 * Cancel terminates the active translation pipeline
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(807605772);
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2869403593);
}

/**
 * Start launches a translation pipeline in background goroutine
 */
export function Start(opts: app$0.TranslateOptions): $CancellablePromise<void> {
    return $Call.ByID(880994998, opts);
}
