//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../lingo-translate/cmd/lingo-desktop/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../../../lingo-translate/pkg/model/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "translation:done": $$createType0,
        "translation:progress": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = main$0.TranslationDonePayload.createFrom;
const $$createType1 = model$0.TranslationProgress.createFrom;

configure();
