package unity

import (
	"bufio"
	"context"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"lingo-translate/pkg/model"
)

var (
	// Unity YAML property regex (e.g. m_Text: "Hello", text: "Start")
	yamlTextPattern = regexp.MustCompile(`(?m)^\s*(?:m_Text|m_text|text|dialogue|caption|description|message)\s*:\s*["']?([^"'\r\n]+)["']?\s*$`)

	// 32-char hex GUID regex
	guidRegex = regexp.MustCompile(`^[0-9a-fA-F]{32}$`)

	// Unity component property path regex
	propPathRegex = regexp.MustCompile(`^(m_|m_Local|m_Name|m_Script|m_GameObject)`)

	// Media/Asset file extensions
	mediaExtRegex = regexp.MustCompile(`(?i)\.(png|jpg|jpeg|gif|bmp|webp|ogg|mp3|wav|m4a|flac|json|mat|prefab|asset|dll|so|exe|meta)$`)
)

// Parser handles Unity games and localization assets
type Parser struct{}

func New() *Parser {
	return &Parser{}
}

func (p *Parser) Name() string {
	return "unity"
}

// Detect checks if the specified directory is a Unity game or asset project
func (p *Parser) Detect(dir string) bool {
	// 1. Check for Unity project folders (Assets/ or ProjectSettings/)
	if fi, err := os.Stat(filepath.Join(dir, "Assets")); err == nil && fi.IsDir() {
		return true
	}
	if fi, err := os.Stat(filepath.Join(dir, "ProjectSettings")); err == nil && fi.IsDir() {
		return true
	}

	// 2. Check for Unity standalone build files (*_Data directory, UnityPlayer.dll/so)
	entries, err := os.ReadDir(dir)
	if err == nil {
		for _, e := range entries {
			name := e.Name()
			if e.IsDir() && strings.HasSuffix(name, "_Data") {
				return true
			}
			if !e.IsDir() && (strings.HasPrefix(name, "UnityPlayer") || name == "UnityCrashHandler64.exe") {
				return true
			}
		}
	}

	// 3. Check for XUnity.AutoTranslator or BepInEx
	if fi, err := os.Stat(filepath.Join(dir, "BepInEx")); err == nil && fi.IsDir() {
		return true
	}
	if fi, err := os.Stat(filepath.Join(dir, "Translation")); err == nil && fi.IsDir() {
		return true
	}

	return false
}

// isTranslatable checks if a string is real text and not an asset ID, path, or code
func isTranslatable(text string) bool {
	trimmed := strings.TrimSpace(text)
	if len(trimmed) < 2 {
		return false
	}
	if guidRegex.MatchString(trimmed) {
		return false
	}
	if propPathRegex.MatchString(trimmed) {
		return false
	}
	if mediaExtRegex.MatchString(trimmed) {
		return false
	}
	// Skip if purely symbols/numbers
	hasLetter := false
	for _, r := range trimmed {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r >= 0x80 {
			hasLetter = true
			break
		}
	}
	return hasLetter
}

// Extract scans Unity files (YAML .asset/.prefab, StreamingAssets .json/.csv, XUnity .txt)
func (p *Parser) Extract(ctx context.Context, dir string) ([]model.TextEntry, *model.ExtractionStats, error) {
	startTime := time.Now()
	var entries []model.TextEntry
	filesScanned := 0
	uniqueSet := make(map[string]bool)

	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == "Temp" || name == "Library" {
				return filepath.SkipDir
			}
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		relPath, _ := filepath.Rel(dir, path)

		switch ext {
		case ".asset", ".prefab", ".unity":
			filesScanned++
			p.extractYAML(path, relPath, &entries, uniqueSet)
		case ".json":
			filesScanned++
			p.extractJSON(path, relPath, &entries, uniqueSet)
		case ".csv", ".tsv":
			filesScanned++
			p.extractCSV(path, relPath, &entries, uniqueSet, ext == ".tsv")
		case ".txt":
			// Check if inside Translation or XUnity folder
			if strings.Contains(relPath, "Translation") || strings.Contains(relPath, "AutoGeneratedTranslations") {
				filesScanned++
				p.extractXUnityText(path, relPath, &entries, uniqueSet)
			}
		}

		return nil
	})

	if err != nil && err != context.Canceled {
		return nil, nil, err
	}

	totalWords := 0
	for _, e := range entries {
		totalWords += len(strings.Fields(e.Source))
	}

	stats := &model.ExtractionStats{
		TotalEntries: len(entries),
		UniqueTexts:  len(uniqueSet),
		TotalWords:   totalWords,
		FilesScanned: filesScanned,
		Duration:     time.Since(startTime),
	}

	return entries, stats, nil
}

func (p *Parser) extractYAML(path, relPath string, entries *[]model.TextEntry, uniqueSet map[string]bool) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		line := scanner.Text()
		matches := yamlTextPattern.FindStringSubmatch(line)
		if len(matches) > 1 {
			txt := strings.TrimSpace(matches[1])
			if isTranslatable(txt) {
				key := fmt.Sprintf("L%d", lineNum)
				*entries = append(*entries, model.TextEntry{
					ID:        fmt.Sprintf("unity_%s_%d", strings.ReplaceAll(relPath, "/", "_"), lineNum),
					FilePath:  relPath,
					KeyPath:   key,
					Source:    txt,
					Status:    model.StatusUntranslated,
					Context:   "Unity YAML Asset",
					UpdatedAt: time.Now(),
				})
				uniqueSet[txt] = true
			}
		}
	}
}

func (p *Parser) extractJSON(path, relPath string, entries *[]model.TextEntry, uniqueSet map[string]bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}

	// Try map[string]interface{}
	var obj map[string]interface{}
	if err := json.Unmarshal(data, &obj); err == nil {
		var walkMap func(prefix string, m map[string]interface{})
		walkMap = func(prefix string, m map[string]interface{}) {
			for k, v := range m {
				currKey := k
				if prefix != "" {
					currKey = prefix + "." + k
				}
				switch val := v.(type) {
				case string:
					if isTranslatable(val) {
						*entries = append(*entries, model.TextEntry{
							ID:        fmt.Sprintf("unity_json_%s_%s", strings.ReplaceAll(relPath, "/", "_"), currKey),
							FilePath:  relPath,
							KeyPath:   currKey,
							Source:    val,
							Status:    model.StatusUntranslated,
							Context:   "Unity JSON Localization",
							UpdatedAt: time.Now(),
						})
						uniqueSet[val] = true
					}
				case map[string]interface{}:
					walkMap(currKey, val)
				}
			}
		}
		walkMap("", obj)
		return
	}

	// Try array of objects
	var arr []map[string]interface{}
	if err := json.Unmarshal(data, &arr); err == nil {
		for i, item := range arr {
			for k, v := range item {
				if val, ok := v.(string); ok && isTranslatable(val) {
					key := fmt.Sprintf("[%d].%s", i, k)
					*entries = append(*entries, model.TextEntry{
						ID:        fmt.Sprintf("unity_json_%s_%d_%s", strings.ReplaceAll(relPath, "/", "_"), i, k),
						FilePath:  relPath,
						KeyPath:   key,
						Source:    val,
						Status:    model.StatusUntranslated,
						Context:   "Unity JSON Table",
						UpdatedAt: time.Now(),
					})
					uniqueSet[val] = true
				}
			}
		}
	}
}

func (p *Parser) extractCSV(path, relPath string, entries *[]model.TextEntry, uniqueSet map[string]bool, isTSV bool) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()

	reader := csv.NewReader(f)
	if isTSV {
		reader.Comma = '\t'
	}
	reader.LazyQuotes = true
	reader.FieldsPerRecord = -1

	rows, err := reader.ReadAll()
	if err != nil || len(rows) < 2 {
		return
	}

	// Inspect header row
	header := rows[0]
	textColIdx := -1
	for i, col := range header {
		lower := strings.ToLower(strings.TrimSpace(col))
		if lower == "source" || lower == "text" || lower == "en" || lower == "english" || lower == "original" {
			textColIdx = i
			break
		}
	}
	if textColIdx == -1 {
		if len(header) >= 2 {
			textColIdx = 1
		} else {
			textColIdx = 0
		}
	}

	for rowIdx := 1; rowIdx < len(rows); rowIdx++ {
		row := rows[rowIdx]
		if textColIdx < len(row) {
			val := strings.TrimSpace(row[textColIdx])
			if isTranslatable(val) {
				keyCol := fmt.Sprintf("Row%d", rowIdx)
				if len(row) > 0 && strings.TrimSpace(row[0]) != "" {
					keyCol = strings.TrimSpace(row[0])
				}
				*entries = append(*entries, model.TextEntry{
					ID:        fmt.Sprintf("unity_csv_%s_%d", strings.ReplaceAll(relPath, "/", "_"), rowIdx),
					FilePath:  relPath,
					KeyPath:   keyCol,
					Source:    val,
					Status:    model.StatusUntranslated,
					Context:   "Unity CSV Localization",
					UpdatedAt: time.Now(),
				})
				uniqueSet[val] = true
			}
		}
	}
}

func (p *Parser) extractXUnityText(path, relPath string, entries *[]model.TextEntry, uniqueSet map[string]bool) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") || strings.HasPrefix(line, "#") {
			continue
		}

		var srcText, tgtText string
		if idx := strings.Index(line, "="); idx != -1 {
			srcText = strings.TrimSpace(line[:idx])
			tgtText = strings.TrimSpace(line[idx+1:])
		} else {
			srcText = line
		}

		if isTranslatable(srcText) {
			status := model.StatusUntranslated
			if tgtText != "" && tgtText != srcText {
				status = model.StatusTranslated
			}
			key := fmt.Sprintf("L%d", lineNum)
			*entries = append(*entries, model.TextEntry{
				ID:        fmt.Sprintf("unity_xunity_%s_%d", strings.ReplaceAll(relPath, "/", "_"), lineNum),
				FilePath:  relPath,
				KeyPath:   key,
				Source:    srcText,
				Target:    tgtText,
				Status:    status,
				Context:   "XUnity.AutoTranslator",
				UpdatedAt: time.Now(),
			})
			uniqueSet[srcText] = true
		}
	}
}

// Inject writes translations into output directory:
// 1. Emits standard XUnity.AutoTranslator translation file (`Translation/th/Text/lingo_translations.txt`)
// 2. Also patches JSON/CSV/YAML files if they exist in source directory
func (p *Parser) Inject(ctx context.Context, sourceDir, outputDir string, entries []model.TextEntry) error {
	if len(entries) == 0 {
		return nil
	}

	// 1. Export XUnity.AutoTranslator format (Universal runtime translation layer for Unity)
	xunityDir := filepath.Join(outputDir, "Translation", "th", "Text")
	if err := os.MkdirAll(xunityDir, 0755); err != nil {
		return fmt.Errorf("failed to create XUnity output dir: %w", err)
	}

	xunityFile := filepath.Join(xunityDir, "lingo_translations.txt")
	f, err := os.Create(xunityFile)
	if err != nil {
		return fmt.Errorf("failed to create xunity translation file: %w", err)
	}
	defer f.Close()

	writer := bufio.NewWriter(f)
	_, _ = writer.WriteString("// Auto-generated by NST (Novelty Translation Tool) for Unity / XUnity.AutoTranslator\n")
	_, _ = writer.WriteString(fmt.Sprintf("// Generated on %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	// Map entries by source file for direct patching
	fileMap := make(map[string][]model.TextEntry)
	for _, e := range entries {
		fileMap[e.FilePath] = append(fileMap[e.FilePath], e)

		// Write to XUnity dictionary
		trans := e.Target
		if trans == "" {
			trans = e.Source
		}
		// Escape newlines for XUnity single-line format
		cleanSrc := strings.ReplaceAll(e.Source, "\r\n", `\n`)
		cleanSrc = strings.ReplaceAll(cleanSrc, "\n", `\n`)
		cleanTgt := strings.ReplaceAll(trans, "\r\n", `\n`)
		cleanTgt = strings.ReplaceAll(cleanTgt, "\n", `\n`)

		_, _ = writer.WriteString(fmt.Sprintf("%s=%s\n", cleanSrc, cleanTgt))
	}
	_ = writer.Flush()

	// 2. Direct patch for editable files (JSON, CSV, YAML)
	for relFile, fileEntries := range fileMap {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		srcFilePath := filepath.Join(sourceDir, relFile)
		destFilePath := filepath.Join(outputDir, relFile)

		// Ensure parent directory exists
		if err := os.MkdirAll(filepath.Dir(destFilePath), 0755); err != nil {
			continue
		}

		ext := strings.ToLower(filepath.Ext(relFile))
		switch ext {
		case ".json":
			p.patchJSON(srcFilePath, destFilePath, fileEntries)
		case ".asset", ".prefab", ".unity":
			p.patchYAML(srcFilePath, destFilePath, fileEntries)
		}
	}

	return nil
}

func (p *Parser) patchJSON(srcPath, destPath string, entries []model.TextEntry) {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return
	}

	translationMap := make(map[string]string)
	for _, e := range entries {
		if e.Target != "" {
			translationMap[e.Source] = e.Target
		}
	}

	content := string(data)
	for src, tgt := range translationMap {
		srcJSON, _ := json.Marshal(src)
		tgtJSON, _ := json.Marshal(tgt)
		content = strings.ReplaceAll(content, string(srcJSON), string(tgtJSON))
	}

	_ = os.WriteFile(destPath, []byte(content), 0644)
}

func (p *Parser) patchYAML(srcPath, destPath string, entries []model.TextEntry) {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return
	}

	translationMap := make(map[string]string)
	for _, e := range entries {
		if e.Target != "" {
			translationMap[e.Source] = e.Target
		}
	}

	content := string(data)
	for src, tgt := range translationMap {
		content = strings.ReplaceAll(content, src, tgt)
	}

	_ = os.WriteFile(destPath, []byte(content), 0644)
}
