// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PublishResult contains response details from Chanomhub
 */
export class PublishResult {
    "success": boolean;
    "download_url": string;
    "file_size_bytes": number;
    "message": string;

    /** Creates a new PublishResult instance. */
    constructor($$source: Partial<PublishResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("download_url" in $$source)) {
            this["download_url"] = "";
        }
        if (!("file_size_bytes" in $$source)) {
            this["file_size_bytes"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishResult($$parsedSource as Partial<PublishResult>);
    }
}
