// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProjectEntry represents metadata of a registered NST translation project
 */
export class ProjectEntry {
    /**
     * Absolute path to .nst workspace file
     */
    "file_path": string;

    /**
     * User-friendly project name
     */
    "display_name": string;

    /**
     * Engine type (rpgm, renpy, etc.)
     */
    "engine_name": string;

    /**
     * Original game root directory
     */
    "project_path": string;
    "source_lang": string;
    "target_lang": string;
    "last_modified": string;
    "total_entries": number;
    "translated_entries": number;
    "translated_percent": number;

    /** Creates a new ProjectEntry instance. */
    constructor($$source: Partial<ProjectEntry> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("engine_name" in $$source)) {
            this["engine_name"] = "";
        }
        if (!("project_path" in $$source)) {
            this["project_path"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("last_modified" in $$source)) {
            this["last_modified"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("total_entries" in $$source)) {
            this["total_entries"] = 0;
        }
        if (!("translated_entries" in $$source)) {
            this["translated_entries"] = 0;
        }
        if (!("translated_percent" in $$source)) {
            this["translated_percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectEntry($$parsedSource as Partial<ProjectEntry>);
    }
}
