// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * MergeStats tracks the metrics of updating a project with a new game version
 */
export class MergeStats {
    "total_new": number;
    "exact_matches": number;
    "fuzzy_matches": number;
    "new_untranslated": number;
    "obsolete_count": number;
    "duration": time$0.Duration;

    /** Creates a new MergeStats instance. */
    constructor($$source: Partial<MergeStats> = {}) {
        if (!("total_new" in $$source)) {
            this["total_new"] = 0;
        }
        if (!("exact_matches" in $$source)) {
            this["exact_matches"] = 0;
        }
        if (!("fuzzy_matches" in $$source)) {
            this["fuzzy_matches"] = 0;
        }
        if (!("new_untranslated" in $$source)) {
            this["new_untranslated"] = 0;
        }
        if (!("obsolete_count" in $$source)) {
            this["obsolete_count"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeStats($$parsedSource as Partial<MergeStats>);
    }
}
