// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ExtractionStats contains summary metrics of an extraction run
 */
export class ExtractionStats {
    "total_entries": number;
    "unique_texts": number;
    "total_words": number;
    "files_scanned": number;
    "duration": time$0.Duration;

    /** Creates a new ExtractionStats instance. */
    constructor($$source: Partial<ExtractionStats> = {}) {
        if (!("total_entries" in $$source)) {
            this["total_entries"] = 0;
        }
        if (!("unique_texts" in $$source)) {
            this["unique_texts"] = 0;
        }
        if (!("total_words" in $$source)) {
            this["total_words"] = 0;
        }
        if (!("files_scanned" in $$source)) {
            this["files_scanned"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractionStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtractionStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtractionStats($$parsedSource as Partial<ExtractionStats>);
    }
}

/**
 * Project represents an active translation project
 */
export class Project {
    "id": string;
    "name": string;

    /**
     * "rpgm-mv", "rpgm-mz", "renpy", etc.
     */
    "engine": string;

    /**
     * Path to game root folder
     */
    "source_path": string;

    /**
     * e.g. "Japanese", "English"
     */
    "source_lang": string;

    /**
     * e.g. "Thai"
     */
    "target_lang": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("source_path" in $$source)) {
            this["source_path"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * TextEntry is the fundamental unit of text to translate
 */
export class TextEntry {
    "id": string;
    "source": string;
    "target"?: string;

    /**
     * Relative to game data dir
     */
    "file_path": string;

    /**
     * JSON path or line number e.g. "events[1].pages[0].parameters[0]"
     */
    "key_path": string;
    "status": TranslationStatus;

    /**
     * Character name, speaker, or location
     */
    "context"?: string;

    /**
     * Service or user that translated it
     */
    "translator"?: string;
    "updated_at": string;

    /** Creates a new TextEntry instance. */
    constructor($$source: Partial<TextEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("key_path" in $$source)) {
            this["key_path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TranslationStatus.$zero;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TextEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextEntry($$parsedSource as Partial<TextEntry>);
    }
}

/**
 * TranslationProgress reports progress during batch translation
 */
export class TranslationProgress {
    "total": number;
    "completed": number;
    "current_file": string;
    "failed": number;
    "percent": number;

    /** Creates a new TranslationProgress instance. */
    constructor($$source: Partial<TranslationProgress> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("current_file" in $$source)) {
            this["current_file"] = "";
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationProgress($$parsedSource as Partial<TranslationProgress>);
    }
}

/**
 * TranslationStatus represents the review/translation lifecycle of an entry
 */
export enum TranslationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusUntranslated = "untranslated",
    StatusTranslated = "translated",
    StatusReviewed = "reviewed",
    StatusApproved = "approved",
    StatusSkipped = "skipped",
};
