package rpgm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"lingo-translate/pkg/model"
)

func TestInjectionDeploy(t *testing.T) {
	tempGame := t.TempDir()

	// Setup mock RPG Maker structure
	dataDir := filepath.Join(tempGame, "data")
	pluginsDir := filepath.Join(tempGame, "js", "plugins")
	_ = os.MkdirAll(dataDir, 0755)
	_ = os.MkdirAll(pluginsDir, 0755)

	// Create a dummy original game file
	origMapContent := `{"displayName":"Starting Town"}`
	_ = os.WriteFile(filepath.Join(dataDir, "Map001.json"), []byte(origMapContent), 0644)

	// Create a dummy plugins.js
	pluginsJsContent := `// Generated by RPG Maker.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic parameters","parameters":{}}
];`
	_ = os.WriteFile(filepath.Join(tempGame, "js", "plugins.js"), []byte(pluginsJsContent), 0644)

	exporter := NewExporter()

	entries := []model.TextEntry{
		{
			FilePath: "Map001.json",
			Source:   "Starting Town",
			Target:   "เมืองเริ่มต้น",
			Status:   model.StatusTranslated,
		},
		{
			FilePath: "Map001.json",
			Source:   "Hello Hero!",
			Target:   "สวัสดีผู้กล้า!",
			Status:   model.StatusTranslated,
		},
	}

	opts := DeployOptions{
		LanguageName:   "Thai",
		OnlyTranslated: true,
	}

	if err := exporter.Deploy(tempGame, entries, opts); err != nil {
		t.Fatalf("Deploy failed: %v", err)
	}

	// 1. Verify config.json exists
	configPath := filepath.Join(tempGame, "lingo_translations", "config.json")
	if _, err := os.Stat(configPath); err != nil {
		t.Fatalf("config.json missing: %v", err)
	}

	// 2. Verify Map001.json and Map001.txt exist in lingo_translations/
	jsonPath := filepath.Join(tempGame, "lingo_translations", "Map001.json")
	if _, err := os.Stat(jsonPath); err != nil {
		t.Fatalf("Map001.json missing: %v", err)
	}

	txtPath := filepath.Join(tempGame, "lingo_translations", "Map001.txt")
	txtBytes, err := os.ReadFile(txtPath)
	if err != nil {
		t.Fatalf("Failed to read Map001.txt: %v", err)
	}
	if !strings.Contains(string(txtBytes), "<<<ORIGINAL>>>\nStarting Town\n<<<TRANSLATED>>>\nเมืองเริ่มต้น\n<<<END>>>") {
		t.Errorf("Map001.txt does not contain expected translation block:\n%s", string(txtBytes))
	}

	// 3. Verify Lingo_TranslationLayer.js was installed in plugins/
	pluginPath := filepath.Join(pluginsDir, "Lingo_TranslationLayer.js")
	fi, err := os.Stat(pluginPath)
	if err != nil || fi.Size() == 0 {
		t.Fatalf("Lingo_TranslationLayer.js was not copied properly, size: %v", fi)
	}

	// 4. Verify plugins.js was patched
	patchedJsBytes, _ := os.ReadFile(filepath.Join(tempGame, "js", "plugins.js"))
	if !strings.Contains(string(patchedJsBytes), `"name":"Lingo_TranslationLayer"`) {
		t.Fatalf("plugins.js was not patched with Lingo_TranslationLayer: %s", string(patchedJsBytes))
	}

	// 5. CRITICAL: Verify original data/Map001.json is NOT modified (Non-Destructive!)
	currentOrigBytes, _ := os.ReadFile(filepath.Join(dataDir, "Map001.json"))
	if string(currentOrigBytes) != origMapContent {
		t.Errorf("Original game file was modified! Expected %s, got %s", origMapContent, string(currentOrigBytes))
	}

	t.Log("Non-destructive Injection Deploy tests passed successfully!")
}
