// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EntryQuery specifies filtering and pagination for text entries
 */
export class EntryQuery {
    "file": string;
    "status": string;
    "search": string;
    "limit": number;
    "offset": number;

    /** Creates a new EntryQuery instance. */
    constructor($$source: Partial<EntryQuery> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("search" in $$source)) {
            this["search"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryQuery($$parsedSource as Partial<EntryQuery>);
    }
}

/**
 * FileSummary contains count of total and translated entries per file
 */
export class FileSummary {
    "path": string;
    "total": number;
    "translated": number;

    /** Creates a new FileSummary instance. */
    constructor($$source: Partial<FileSummary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("translated" in $$source)) {
            this["translated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): FileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileSummary($$parsedSource as Partial<FileSummary>);
    }
}

/**
 * WorkspaceStats contains overall translation progress metrics
 */
export class WorkspaceStats {
    "total": number;
    "translated": number;
    "pending": number;
    "percent": number;

    /** Creates a new WorkspaceStats instance. */
    constructor($$source: Partial<WorkspaceStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("translated" in $$source)) {
            this["translated"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceStats instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceStats($$parsedSource as Partial<WorkspaceStats>);
    }
}
