// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProviderConfig holds configuration for constructing a translator provider
 */
export class ProviderConfig {
    /**
     * "mock", "gemini", "openai", "google"
     */
    "name": string;
    "api_key": string;
    "model": string;
    "base_url": string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

/**
 * PublishOptions configures translation mod publishing to Chanomhub
 */
export class PublishOptions {
    "game_dir": string;
    "slug": string;
    "token": string;
    "language": string;
    "api_base": string;
    "storage_url": string;

    /** Creates a new PublishOptions instance. */
    constructor($$source: Partial<PublishOptions> = {}) {
        if (!("game_dir" in $$source)) {
            this["game_dir"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("api_base" in $$source)) {
            this["api_base"] = "";
        }
        if (!("storage_url" in $$source)) {
            this["storage_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishOptions($$parsedSource as Partial<PublishOptions>);
    }
}

/**
 * SystemOneOptions configures the auxiliary decision engine (TypeSafe AI Jev / Heuristic)
 */
export class SystemOneOptions {
    "enabled": boolean;
    "provider": string;
    "api_key": string;
    "base_url"?: string;
    "confidence_threshold"?: number;
    "filter_ambiguous_code": boolean;
    "accept_ui_drafts": boolean;
    "verify_qa": boolean;

    /** Creates a new SystemOneOptions instance. */
    constructor($$source: Partial<SystemOneOptions> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("filter_ambiguous_code" in $$source)) {
            this["filter_ambiguous_code"] = false;
        }
        if (!("accept_ui_drafts" in $$source)) {
            this["accept_ui_drafts"] = false;
        }
        if (!("verify_qa" in $$source)) {
            this["verify_qa"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemOneOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemOneOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemOneOptions($$parsedSource as Partial<SystemOneOptions>);
    }
}

/**
 * TranslateOptions configures a batch translation run
 */
export class TranslateOptions {
    "provider": ProviderConfig;
    "fast_provider"?: ProviderConfig;
    "auto_route_short"?: boolean;
    "max_short_len"?: number;
    "system_one"?: SystemOneOptions;
    "source_lang": string;
    "target_lang": string;
    "batch_size": number;
    "concurrency": number;

    /**
     * "all", "untranslated", or file path
     */
    "scope": string;

    /** Creates a new TranslateOptions instance. */
    constructor($$source: Partial<TranslateOptions> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = (new ProviderConfig());
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("batch_size" in $$source)) {
            this["batch_size"] = 0;
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslateOptions {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField0_0($$parsedSource["provider"]);
        }
        if ("fast_provider" in $$parsedSource && $$parsedSource["fast_provider"]) {
            $$parsedSource["fast_provider"] = $$createField0_0($$parsedSource["fast_provider"]);
        }
        if ("system_one" in $$parsedSource && $$parsedSource["system_one"]) {
            $$parsedSource["system_one"] = SystemOneOptions.createFrom($$parsedSource["system_one"]);
        }
        return new TranslateOptions($$parsedSource as Partial<TranslateOptions>);
    }
}

// Private type creation functions
const $$createType0 = ProviderConfig.createFrom;

