// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ProviderConfig holds configuration for constructing a translator provider
 */
export class ProviderConfig {
    /**
     * "mock", "gemini", "openai", "google"
     */
    "name": string;
    "api_key": string;
    "model": string;
    "base_url": string;
    "timeout"?: time$0.Duration;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

/**
 * ProviderInfo represents metadata about an available translation provider
 */
export class ProviderInfo {
    "name": string;
    "display_name": string;
    "description"?: string;
    "is_custom": boolean;
    "base_url"?: string;
    "default_model"?: string;
    "available_models"?: string[];

    /** Creates a new ProviderInfo instance. */
    constructor($$source: Partial<ProviderInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("is_custom" in $$source)) {
            this["is_custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderInfo {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("available_models" in $$parsedSource) {
            $$parsedSource["available_models"] = $$createField6_0($$parsedSource["available_models"]);
        }
        return new ProviderInfo($$parsedSource as Partial<ProviderInfo>);
    }
}

/**
 * PublishOptions configures translation mod publishing to Chanomhub
 */
export class PublishOptions {
    "workspace"?: string;
    "patch_file"?: string;
    "game_dir"?: string;
    "slug"?: string;
    "token": string;
    "language"?: string;
    "credit_to"?: string;
    "api_base"?: string;
    "storage_url"?: string;

    /** Creates a new PublishOptions instance. */
    constructor($$source: Partial<PublishOptions> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishOptions($$parsedSource as Partial<PublishOptions>);
    }
}

/**
 * SystemOneOptions configures the auxiliary decision engine (TypeSafe AI Jev / Heuristic)
 */
export class SystemOneOptions {
    "enabled": boolean;
    "provider": string;
    "api_key": string;
    "base_url"?: string;
    "confidence_threshold"?: number;
    "filter_ambiguous_code": boolean;
    "accept_ui_drafts": boolean;
    "verify_qa": boolean;

    /** Creates a new SystemOneOptions instance. */
    constructor($$source: Partial<SystemOneOptions> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("filter_ambiguous_code" in $$source)) {
            this["filter_ambiguous_code"] = false;
        }
        if (!("accept_ui_drafts" in $$source)) {
            this["accept_ui_drafts"] = false;
        }
        if (!("verify_qa" in $$source)) {
            this["verify_qa"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemOneOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemOneOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemOneOptions($$parsedSource as Partial<SystemOneOptions>);
    }
}

/**
 * TranslateOptions configures a batch translation run
 */
export class TranslateOptions {
    "provider": ProviderConfig;
    "fast_provider"?: ProviderConfig | null;
    "auto_route_short"?: boolean;
    "max_short_len"?: number;
    "system_one"?: SystemOneOptions | null;
    "source_lang": string;
    "target_lang": string;
    "batch_size": number;
    "concurrency": number;

    /**
     * "all", "untranslated", or file path
     */
    "scope": string;
    "stream"?: boolean;

    /**
     * "json" (default) or "line"
     */
    "format"?: string;

    /**
     * e.g. "standard", "nsfw", "vn_romance", "fantasy_rpg", etc.
     */
    "style"?: string;

    /**
     * Custom system prompt instruction
     */
    "prompt"?: string;

    /** Creates a new TranslateOptions instance. */
    constructor($$source: Partial<TranslateOptions> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = (new ProviderConfig());
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("batch_size" in $$source)) {
            this["batch_size"] = 0;
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslateOptions {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField0_0($$parsedSource["provider"]);
        }
        if ("fast_provider" in $$parsedSource) {
            $$parsedSource["fast_provider"] = $$createField1_0($$parsedSource["fast_provider"]);
        }
        if ("system_one" in $$parsedSource) {
            $$parsedSource["system_one"] = $$createField4_0($$parsedSource["system_one"]);
        }
        return new TranslateOptions($$parsedSource as Partial<TranslateOptions>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProviderConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = SystemOneOptions.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
